// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddUser(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddUser'](arg1, arg2, arg3);
}

export function GetAllUsers() {
  return window['go']['main']['App']['GetAllUsers']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
