// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddUser(arg1:string,arg2:string,arg3:number):Promise<main.usergovnas>;

export function GetAllUsers():Promise<Array<main.usergovnas>>;

export function Greet(arg1:string):Promise<string>;
